const songs = [
  "/music/01 The Trail.mp3",
  "/music/02 Geralt of Rivia.mp3",
  "/music/03 The Nightingale.mp3",
  "/music/04 A Story You Won't Believe.mp3",
  "/music/05 Drink Up, There's More!.mp3",
  "/music/06 The Wolven Storm.mp3",
  "/music/07 Another Round For Everyone.mp3",
  "/music/08 Hail To Caranthir.mp3",
  "/music/09 The Fields of Ard Skellig.mp3",
  "/music/10 Cloak and Dagger.mp3",
  "/music/11 Back On The Path.mp3",
  "/music/12 Merchants of Novigrad.mp3",
  "/music/13 Kaer Morhen.mp3",
  "/music/14 The Vagabond.mp3",
  "/music/15 Yes, I Do....mp3",
  "/music/16 After the Storm.mp3",
  "/music/17 Farewell, Old Friend.mp3",
  "/music/18 Ladies of the Woods.mp3",
  "/music/19 Hunt Or Be Hunted.mp3",
  "/music/20 Hjalmar's Axe.mp3",
  "/music/21 Mystery Man.mp3",
  "/music/22 Forefather's Eve.mp3",
  "/music/23 On The Champs-Desoles.mp3",
  "/music/24 The Slopes Of The Blessure.mp3",
  "/music/25 For Honor! For Toussaint!.mp3",
  "/music/26 Guillaume Versus The Shaelmaar.mp3",
  "/music/27 The Beast Of Beauclair.mp3",
  "/music/28 Evening In The Tavern.mp3",
  "/music/29 Tavern At The End Of World.mp3",
  "/music/30 A Watering Hole In The Harbor.mp3",
  "/music/31 Riches And Glory.mp3",
  "/music/32 Monstrous Might.mp3",
  "/music/33 The Mighty Jarl Of Skellige.mp3",
  "/music/34 The Musty Scent Of Fresh Pate.mp3",
  "/music/35 Clever Clogs.mp3",
  "/music/36 Another Round, Perhaps.mp3",
  "/music/37 Searching for Cecilia Bellant.mp3",
  "/music/38 The Mandragora.mp3",
  "/music/39 How About A Round Of Gwent.mp3",
  "/music/40 A Risky Game.mp3",
  "/music/41 Just Punishment.mp3",
  "/music/42 Lair Of The Beast.mp3",
  "/music/43 No Place Like Home.mp3",
  "/music/44 Toss A Coin To Your Witcher.mp3",
  "/music/45 Burn Butcher Burn.mp3",
  "/music/46 The Golden One.mp3",
  "/music/47 Her Sweet Kiss.mp3",
  "/music/48 Song of the Seven.mp3",
  "/music/49 Whoreson Prison Blues.mp3",
  "/music/50 Geralt of Rivia (Netflix).mp3",
];

export default songs;
