const soundEffects = [
  "/sounds/mouseHover.mp3",
  "/sounds/startGame.mp3",
  "/sounds/coinFlip.mp3",
  "/sounds/turnPlayer.mp3",
  "/sounds/turnOpponent.mp3",
  "/sounds/roundWin.mp3",
  "/sounds/roundLoss.mp3",
  "/sounds/roundDraw.mp3",
  "/sounds/gameWin.mp3",
  "/sounds/gameLoss.mp3",
  "/sounds/openDeck.mp3",
  "/sounds/redrawCardsStart.mp3",
  "/sounds/redrawCardsEnd.mp3",
  "/sounds/redrawCard.mp3",
  "/sounds/addCard.mp3",
  "/sounds/factionAbility.mp3",
  "/sounds/cardBond.mp3",
  "/sounds/cardDecoy.mp3",
  "/sounds/cardMedic.mp3",
  "/sounds/cardHero.mp3",
  "/sounds/cardHorn.mp3",
  "/sounds/cardMelee.mp3",
  "/sounds/cardMorale.mp3",
  "/sounds/cardRanged.mp3",
  "/sounds/cardScorch.mp3",
  "/sounds/cardSiege.mp3",
  "/sounds/cardSpy.mp3",
  "/sounds/cardSummon.mp3",
  "/sounds/weatherClear.mp3",
  "/sounds/weatherFrost.mp3",
  "/sounds/weatherFog.mp3",
  "/sounds/weatherRain.mp3",
  "/sounds/weatherStorm.mp3",
  "/sounds/challengeComplete.mp3",
];

export default soundEffects;
